# -*- coding: utf-8 -*-
"""Q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPfjuJt-hkIIYUO2gLcJP3wc2IOJLkcd
"""

import math
import random
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

try:
    from tqdm.auto import tqdm
except Exception:
    !pip -q install tqdm
    from tqdm.auto import tqdm

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

def build_k_grid(k_min=0.0, k_max=5.0, step_coarse=0.1, step_fine=0.02, critical_lo=0.8, critical_hi=1.2):
    ks = []
    k = k_min
    while k <= k_max + 1e-12:
        ks.append(round(k, 4))
        if critical_lo <= k <= critical_hi:
            k += step_fine
        else:
            k += step_coarse
    return np.unique(np.array(ks, dtype=float))

def er_graph(N, k_avg, seed=None):
    p = k_avg / (N - 1)
    return nx.erdos_renyi_graph(n=N, p=p, seed=seed, directed=False)

def compute_S_and_savg(G):

    comps = list(nx.connected_components(G))
    sizes = np.array([len(c) for c in comps], dtype=float)
    if sizes.size == 0:
        return 0.0, 0.0

    NG = float(sizes.max())
    S = NG / G.number_of_nodes()

    if sizes.size == 1:
        s_avg = 0.0
    else:
        idx = int(np.argmax(sizes))
        rest = np.delete(sizes, idx)
        s_avg = float(np.mean(rest)) if rest.size > 0 else 0.0

    return S, s_avg

def sweep_k(N=1000, realizations=50, desc_prefix="", **grid_kwargs):

    ks = build_k_grid(**grid_kwargs)
    S_mean = np.zeros_like(ks, dtype=float)
    s_mean = np.zeros_like(ks, dtype=float)

    outer = tqdm(range(len(ks)), desc=f"{desc_prefix} Sweep <k> (N={N})", leave=True)
    for i in outer:
        k_avg = float(ks[i])

        Ss = []
        ss = []

        inner = tqdm(range(realizations), desc=f"  realizations @ <k>={k_avg:.2f}", leave=False)
        for r in inner:
            seed = SEED + (i + 1) * 100000 + r
            G = er_graph(N, k_avg, seed=seed)
            S, s_avg = compute_S_and_savg(G)
            Ss.append(S)
            ss.append(s_avg)

        S_mean[i] = float(np.mean(Ss))
        s_mean[i] = float(np.mean(ss))

        outer.set_postfix({"<k>": f"{k_avg:.2f}", "S": f"{S_mean[i]:.3f}", "<s>": f"{s_mean[i]:.3f}"})

    return ks, S_mean, s_mean

N0 = 1000
REALIZATIONS = 50

ks, S_vals, s_vals = sweep_k(
    N=N0,
    realizations=REALIZATIONS,
    desc_prefix="(Q3 a/b)",
    k_min=0.0, k_max=5.0,
    step_coarse=0.1, step_fine=0.02,
    critical_lo=0.8, critical_hi=1.2
)

plt.figure(figsize=(7, 4))
plt.plot(ks, S_vals, marker="o", markersize=3)
plt.axvline(1.0, linestyle="--")
plt.xlabel("<k>")
plt.ylabel("S = NG/N")
plt.title("Figure (Q3-b-1): Order parameter S vs <k> (N=1000)")
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(7, 4))
plt.plot(ks, s_vals, marker="o", markersize=3)
plt.axvline(1.0, linestyle="--")
plt.xlabel("<k>")
plt.ylabel("<s> (excluding largest component)")
plt.title("Figure (Q3-b-2): Average finite-cluster size <s> vs <k> (N=1000)")
plt.grid(True)
plt.tight_layout()
plt.show()

k_c_est = float(ks[int(np.argmax(s_vals))])
print("\nEstimated critical point from peak of <s>:", k_c_est)


Ns = [100, 1000, 10000]
S_curves = {}

for N in Ns:
    ks_c, S_c, _ = sweep_k(
        N=N,
        realizations=REALIZATIONS,
        desc_prefix="(Q3 c)",
        k_min=0.0, k_max=5.0,
        step_coarse=0.1, step_fine=0.02,
        critical_lo=0.8, critical_hi=1.2
    )
    S_curves[N] = (ks_c, S_c)

plt.figure(figsize=(7, 4))
for N in Ns:
    plt.plot(S_curves[N][0], S_curves[N][1], marker="o", markersize=2, label=f"N={N}")
plt.axvline(1.0, linestyle="--")
plt.xlabel("<k>")
plt.ylabel("S = NG/N")
plt.title("Figure (Q3-c): Finite-size effect — S vs <k> for multiple N")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

print("\nS values near <k>=1 for different N:")
for N in Ns:
    ksN, SN = S_curves[N]
    idx = int(np.argmin(np.abs(ksN - 1.0)))
    print(f"N={N:5d} : <k>={ksN[idx]:.2f}  S={SN[idx]:.5f}")

Ncrit = 10000
kcrit = 1.0
print("\nBuilding one critical graph for Q3(d): N=10000, <k>=1 ...")
Gcrit = er_graph(Ncrit, kcrit, seed=SEED + 999)

comp_sizes = np.array([len(c) for c in nx.connected_components(Gcrit)], dtype=int)

def log_binned_distribution(sizes, num_bins=30):
    """Return (bin_centers, P(bin)) with log-spaced bins."""
    sizes = np.asarray(sizes, dtype=int)
    sizes = sizes[sizes > 0]
    s_min = sizes.min()
    s_max = sizes.max()

    edges = np.unique(np.logspace(np.log10(s_min), np.log10(s_max), num_bins).astype(int))
    edges = np.unique(np.concatenate([edges, [s_max + 1]]))
    edges = np.sort(edges)

    counts, bin_edges = np.histogram(sizes, bins=edges)
    left = bin_edges[:-1]
    right = bin_edges[1:]
    centers = np.sqrt(left * right)  # geometric mean
    P = counts / counts.sum() if counts.sum() > 0 else counts.astype(float)

    mask = counts > 0
    return centers[mask].astype(float), P[mask].astype(float)

bin_c, Pbin = log_binned_distribution(comp_sizes, num_bins=30)

plt.figure(figsize=(7, 4))
plt.plot(np.log10(bin_c), np.log10(Pbin), marker="o", linestyle="None")
plt.xlabel("log10(s)")
plt.ylabel("log10(P(s))")
plt.title("Figure (Q3-d): Log-binned component size distribution at criticality (N=10000, <k>=1)")
plt.grid(True)
plt.tight_layout()
plt.show()

def fit_alpha(bin_centers, P, s_min_fit=10):
    """Fit log10(P) = a - alpha log10(s) for s >= s_min_fit."""
    s = np.asarray(bin_centers)
    p = np.asarray(P)
    mask = (s >= s_min_fit) & (p > 0)
    x = np.log10(s[mask])
    y = np.log10(p[mask])
    if x.size < 2:
        return None
    m, a = np.polyfit(x, y, 1)
    alpha = -m
    return float(alpha), float(m), float(a)

alpha_fit = fit_alpha(bin_c, Pbin, s_min_fit=10)
print("\nCritical distribution fit (log-binned, s>=10):", alpha_fit)
print("Theoretical prediction at criticality: alpha = 3/2 ≈ 1.5")

